
[functions]
  included_files = ["./src/lib/images/*", "src/lib/RetroByte.ttf", "./src/lib/Star-Crush.otf"]

  
[build]
  base    = ""
  publish = "dist"
  command = "npm run build"
  [build.processing]
    skip_processing = true